### ISSUE TITLE
[native_pdf_view] Build step for pdfium failed

### ISSUE THREAD

**Issue by CaroloFa** [ScerIO/packages.flutter#242]
Hey, great package, thank you for your work! 

**Describe the bug**
I have some troubles when building for Windows.
I get following error after calling `flutter run -d windows`:

```
CMake Error at flutter/ephemeral/.plugin_symlinks/native_pdf_renderer/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
```

**To Reproduce**
1. create new flutter project
2. install native_pdf_view
3. flutter run -d windows

**Expected behavior**
A Successful build

**Screenshots**

**Smartphone (please complete the following information):**
 - Desktop Windows-x64

**Additional context**
- I'm developing on a Windows machine with Windows 10 SDK version 10.0.18362.0
- Flutter (Channel beta, 2.8.0-3.1.pre,)
- I ran the cmd as admin.

**Comment by milkyway044** [comment]
+1

**Comment by Salam-pc** [comment]
same here

**Comment by milkyway044** [comment]
@CaroloFa CaroloFa @Salam-pc  work around: https://github.com/rbcprolabs/packages.flutter/pull/233#issuecomment-970246427

**Comment by CaroloFa** [comment]
> @CaroloFa @Salam-pc work around: [#233 (comment)](https://github.com/rbcprolabs/packages.flutter/pull/233#issuecomment-970246427)

Ty for letting us now, it builds successfully with that workaround. Sadly the swipe and zoom does not work, but that is probably another issue

**Comment by barbalex** [comment]
https://github.com/rbcprolabs/packages.flutter/pull/233#issuecomment-970246427 does not work in my case

any other way?

**Comment by SergeShkurko** [comment]
Fixed in [pdfx] package
