### ISSUE TITLE
[epub view] If there is no subtitle, just loading..

### ISSUE THREAD

**Issue by Tahaylmz** [ScerIO/packages.flutter#292]
Hello, 

I wonder, is there any way i can open e pub without subtitles? 
Do i need to update cfi to do this? 
If so, what should I write in the cfi section?

**Comment by Tahaylmz** [comment]
Is there anyone to answer my question?
If there are no chapters in the epub, epub view not opening.

**Comment by papakay** [comment]
@Tahaylmz please were you able to resolve this?

**Comment by Tahaylmz** [comment]
Hi @papakay, 
Check the solution this issue; 
https://stackoverflow.com/questions/72228668/epub-viewer-package-release-build-crash/72290447#72290447
Hope this is the answer.
