### ISSUE TITLE
Unable to Build App - pdfx 2.0.1.1+2 depends on photo_view 0.13.0

### ISSUE THREAD

**Issue by LarssK-TS** [ScerIO/packages.flutter#304]
**Describe the bug**
Photo View package has a new version 0.14.0 which resolves a number of important issues https://pub.dev/packages/photo_view/changelog
However upgrading this package means any app using the pdfx won't build.

**To Reproduce**
1. upgrade photo_view package to ^0.14.0
```
Because pdfx 2.0.1+2 depends on photo_view ^0.13.0 and no versions of pdfx match >2.0.1+2 <3.0.0, pdfx ^2.0.1+2 requires photo_view ^0.13.0.
So, because exampleapp depends on both photo_view ^0.14.0 and pdfx ^2.0.1+2, version solving failed.
```
**Expected behavior**
new version of pdfx is required in order to build app

Thank you

**Comment by harry-dickson** [comment]
While you wait for a new package, you can try this in pubspec.yaml:

```
dependencies:
  ...
  pdfx:   pdfx: ^2.0.1+1
  ...

dependency_overrides:
  photo_view: ^0.14.0  
```

**Comment by rivella50** [comment]
Upvote for this upgrade request.

**Comment by bhayatus** [comment]
Could we possibly get a new pub.dev release?

**Comment by SergeShkurko** [comment]
Already upgraded in actual package release (2.2.0)
