### ISSUE TITLE
pdfx 2.0.1+2 depends on device_info_plus ^3.2.1

### ISSUE THREAD

**Issue by zs-dima** [ScerIO/packages.flutter#312]
Because pdfx 2.0.1+2 depends on device_info_plus ^3.2.1 and no versions of pdfx match >2.0.1+2 <3.0.0, pdfx ^2.0.1+2 requires device_info_plus ^3.2.1.
So, because app depends on both device_info_plus ^4.0.0 and pdfx ^2.0.1+2, version solving failed.
exit code 1

**Comment by SergeShkurko** [comment]
Dependency upgraded  https://pub.dev/packages/pdfx/versions/2.1.1
