### ISSUE TITLE
[pdfx] [Request] Release latest version

### ISSUE THREAD

**Issue by mzdm** [ScerIO/packages.flutter#315]
Please release the latest version of pdx, it has some commits which are not available on pub.dev yet.
Waiting specifically for this (https://github.com/ScerIO/packages.flutter/commit/59e5004a88ce3b1c30ccc62ce451845838727e9e), which fixed memory leak. Thanks

**Comment by SergeShkurko** [comment]
Released in https://pub.dev/packages/pdfx/versions/2.1.0
