### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by sgehrman** [ScerIO/packages.flutter#318]
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/pdfx-2.1.1/lib/src/renderer/web/platform.dart:2:8: Error: Not found: 'dart:html'
ERROR: import 'dart:html' as html;
ERROR:        ^
ERROR: ../../../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:13:8: Error: Not found: 'dart:html'
ERROR: import 'dart:html' as html;
ERROR:        ^
ERROR: ../../../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:6:8: Error: Not found: 'dart:html'
ERROR: import 'dart:html' as html;
ERROR:        ^
ERROR: ../../../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:5:8: Error: Not found: 'dart:html'
ERROR: import 'dart:html';
ERROR:        ^
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/pdfx-2.1.1/lib/src/renderer/web/platform.dart:3:8: Error: Not found: 'dart:js'
ERROR: import 'dart:js' as js;
ERROR:        ^
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/pdfx-2.1.1/lib/src/renderer/web/pdfjs.dart:22:8: Error: Not found: 'dart:html'
ERROR: import 'dart:html';
ERROR:        ^
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:8:1: Error: Not found: 'dart:js'
ERROR: export 'dart:js' show allowInterop, allowInteropCaptureThis;
ERROR: ^
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
ERROR: export 'dart:js_util';
ERROR: ^
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/pdfx-2.1.1/lib/src/renderer/web/pdfjs.dart:23:8: Error: Not found: 'dart:js_util'
ERROR: import 'dart:js_util';
ERROR:        ^
ERROR: ../../../../.pub-cache/hosted/pub.dartlang.org/pdfx-2.1.1/lib/src/renderer/web/document/page.dart:2:8: Error: Not found: 'dart:html'

**Comment by sgehrman** [comment]
more info

pdfx: 2.0.1+2 works

pdfx: 2.0.1+3 fails
2.1.1 fails

I'm building a linux desktop app

**Comment by ekasetiawans** [comment]
I'm facing this issue too

**Comment by SuryaSharpsell** [comment]
Facing the same issue too

**Comment by ekuleshov** [comment]
Same issue with 2.1.1 when building macos and ios targets

**Comment by Yoda-Man** [comment]
Same issue

**Comment by YorchUCAB** [comment]
Same error here

**Comment by natdab** [comment]
Same issue. Seems to be trying to build/include web methods for use on a native platform. Is there a more specific include that won't build the web platform code to use to negate this?
