### ISSUE TITLE
Page crash after rendering many pages in Flutter Web on Google Chrome

### ISSUE THREAD

**Issue by timovandeput** [ScerIO/packages.flutter#325]
**Describe the bug**
The browser page crashes after opening a PDF and rendering a single page for more than 100 times.

**To Reproduce**
1. Loaded a PDF into memory.
2. For every render open a new PdfDocument from this buffer.
3. Render a single page per render.
4. Chrome crashes the page with error code 5

**Expected behavior**

**Environment**
 - pdfx version: 2.0.1+2 on Flutter 3.0.4
 - Device: Chrome web browser
 - OS: Experienced on both MacOS 12.4 and Windows 11

**Additional context**
(none)

**Comment by timovandeput** [comment]
This is the core of the code we are using to render a single page from the PDF document:
```
final pdfDocument = await PdfDocument.openData(bytes);
final page = await document.getPage(pageNumber);
final imgPDF = await page.render(width: page.width, height: page.height);
return imgPDF!.bytes;
```

**Comment by SergeShkurko** [comment]
Hello
Page & Document requires call for close `page.close()` & `pdfDocument.close()`
Also i not recommend render > 3-5 documents in parallel
it is desirable to do this sequentially

This process is quite resource intensive.
