### ISSUE TITLE
Increase the kotlin version

### ISSUE THREAD

**Issue by SuryaSharpsell** [ScerIO/packages.flutter#328]
After upgrading to latest version of flutter getting the incompatible version of Kotlin error in multiple files.  

Since, pdfx version 2.1.1 is using Kotlin 1.1.5 which is older version of Kotlin.

**Comment by SergeShkurko** [comment]
Kotlin and build tools upgraded
https://github.com/ScerIO/packages.flutter/commit/3ace68ffb1aff23da6590ee31b478af6bf24c638#diff-421cc0b5a94bd418674284487783fcbed81e058e5dfbc4ff00f8eb94f6f8f702L5-R5
