### ISSUE TITLE
device_info_plus library bug. Required named parameter 'userName' must be provided AND Found this candidate, but the arguments don't match

### ISSUE THREAD

**Issue by Stachuu87** [ScerIO/packages.flutter#339]
Native_pdf_viewer in version 6.0.1+1 depends on device_info_plus package, which has a bug.
More info is available in issue [#1003](https://github.com/fluttercommunity/plus_plugins/issues/1003)

error occurs during build

Smartphone:
checked on 3 different devices (both iOS, android)

Additional context:
Issue on device_info_plus is still open, no permanent fix available, but there is a workaround proposed.
More info available on issue site.

**Comment by joelmaia7** [comment]
I had the same problem.

**Comment by Stachuu87** [comment]
Seems to be fixed by device_info_plus
More info at: [#1000](https://github.com/fluttercommunity/plus_plugins/issues/1000)
