### ISSUE TITLE
File name seems changed on PdfDocument.openFile

### ISSUE THREAD

**Issue by arualana** [ScerIO/packages.flutter#364]
I pass a url as a string, for example

https://www.somedomain.com/my.pdf

this file exists and I can open it in my broser.

Then I do

```
   final pdfPinchController = PdfControllerPinch(
            document: PdfDocument.openFile(url),
          );

```
And I when trying to render the pdf 
```

return PdfViewPinch(
        controller: pdfPinchController,
      );
```

I get a buch of errors on the screen about r`ender exception` and `file not found`, and none in the console, which shows only this:

`OpenFileDocument. File: https:/www.somedomain.com/my.pdf`

With only one slash after https:

**Comment by erlangparasu** [comment]
got same issue
