### ISSUE TITLE
[pdfx] v2.3.0 incompatible with device_info_plus v9.0.2

### ISSUE THREAD

**Issue by HongMenghak** [ScerIO/packages.flutter#408]
When add pdfx v2.3.0 and device_info_plus v9.0.2 to pubspec.yml it show message as below:
Because pdfx 2.3.0 depends on device_info_plus ^4.0.0 and no versions of pdfx match >2.3.0 <3.0.0, pdfx ^2.3.0 requires device_info_plus ^4.0.0.
So, because sample_proj depends on both pdfx ^2.3.0 and device_info_plus ^9.0.2, version solving failed.

**Describe the solution you'd like**
update pdfx to support with device_info_plus latest version

**Comment by rushikesh145** [comment]
I am getting this issue when I upgraded flutter SDK to latest version, please update the plugin as it's not been updated from past 7 months.

**Comment by rivella50** [comment]
Same here. I have 2 other packages in my Flutter project which i cannot upgrade because of pdfx.
Thanks for releasing a new version.

**Comment by thudaydelight** [comment]
please update for device_info_plus 9.0.2

**Comment by hedbladucf** [comment]
We've been asking for a release for this project for the past few months and nothing so far. Is it safe to assume this project is no longer being maintained?

**Comment by rivella50** [comment]
> We've been asking for a release for this project for the past few months and nothing so far. Is it safe to assume this project is no longer being maintained?

Seems so. Serge is from Russia, perhaps he is at war...
Is someone capable of taking his projects over (at least temporarily)?

**Comment by hedbladucf** [comment]
> > We've been asking for a release for this project for the past few months and nothing so far. Is it safe to assume this project is no longer being maintained?
> 
> Seems so. Serge is from Russia, perhaps he is at war... Is someone capable of taking his projects over (at least temporarily)?

Yeah that is fair. I hope he isn't, but understand that he might have other priorities. I like PDFX but just really wish that it wouldn't block me from staying up to date with other packages I currently use. I can't find another option besides Syncfusion, which would unfortunately cost money for the organization I work for. Anyone have any ideas for a replacement?

**Comment by hedbladucf** [comment]
> Hey Guys, I was facing the same incompatibility issues with pdfx, but when I checked the .yaml of the repo, the dependencies are all updated so I thought of directly using the git repo instead of the published package & it worked, you can try the solution below,
> 
> ```
> 
> pdfx:
>     git:
>       url: https://github.com/ScerIO/packages.flutter.git
>       ref: main # branch name
>       path: packages/pdfx
> ```

Thanks for the tip. I updated to use the git link and it worked for me.

**Comment by smunoz-ls** [comment]
> Hey Guys, I was facing the same incompatibility issues with pdfx, but when I checked the .yaml of the repo, the dependencies are all updated so I thought of directly using the git repo instead of the published package & it worked, you can try the solution below,
> 
> ```
> 
> pdfx:
>     git:
>       url: https://github.com/ScerIO/packages.flutter.git
>       ref: main # branch name
>       path: packages/pdfx
> ```

I could not make it work with device_info_plus `^9.0.2`, `main` needs to be updated to `^9.0.0`

**Comment by HongMenghak** [comment]
Since the updated of pdfx v2.4.0 solve this issue, I'm gonna close this.
