### ISSUE TITLE
Publish new version to pub.dev

### ISSUE THREAD

**Issue by eliudio** [ScerIO/packages.flutter#467]
This is now a real problem: https://stackoverflow.com/questions/77517742/error-type-decodercallback-not-found-imagestreamcompleter-loadpdfpageimagep

Flutter upgrade has happened, and DecoderCallback is depricated. However, the current version on pub.dev of pdfx 2.5.0 still contains references to  DecoderCallback. So ones people - like me - upgrade flutter, pdfx breaks.

As the solution on stackoverflow shows, referring to the version on git fixes the problem.

Also works is forking / cloning your version and referencing from local disk.

However, neither of these solutiosn allow people to be used in packages that need to be published to pub.dev also: these require actual packages available on pub.dev

So, hence: please publish the latest master version of pdfx to pub.dev

**Comment by ManuelRauber** [comment]
There is already a long discussion about this, see #463 - please close this issue @eliudio.
