### ISSUE TITLE
Error in Pdfx v2.5.0: 'DecoderCallback' Type Issue in PdfPageImageProvider

### ISSUE THREAD

**Issue by Murtaza-Tn** [ScerIO/packages.flutter#475]
I encountered an issue with Pdfx v2.5.0 where the 'DecoderCallback' type is not recognized in the PdfPageImageProvider class. This results in the error "Type 'DecoderCallback' not found" and "The method 'instantiateImageCodec' isn't defined for the class 'PdfPageImageProvider'".

Use Pdfx v2.5.0 in a Flutter project.
Observe the error related to 'DecoderCallback' and 'instantiateImageCodec'.

I expected the Pdfx package to function without errors related to 'DecoderCallback' and 'instantiateImageCodec' when using PdfPageImageProvider.

Screenshots
![pdfx issue](https://github.com/ScerIO/packages.flutter/assets/114286627/7a47e397-e6ff-4b78-a385-967fce487b3f)

Flutter Environment
Flutter 3.16.5 
Dart 3.2.3 

I am using Pdfx v2.5.0 in a Flutter project to render PDF documents. The error occurs specifically in the PdfPageImageProvider class when attempting to load PDF pages. If there's any additional information required, please let me know.

**Comment by zezo357** [comment]
@Murtaza-Tn https://github.com/ScerIO/packages.flutter/issues/448#issuecomment-1813991815 its fixed on Github but not published on pub.dev

**Comment by Murtaza-Tn** [comment]
@zezo357 @SergeShkurko  Could you please provide an estimated timeline for when the fix will be published on pub.dev?

**Comment by zezo357** [comment]
> @zezo357 @SergeShkurko  Could you please provide an estimated timeline for when the fix will be published on pub.dev? 

I am not the maintainer of the package, I just saw your issue and I had it too,


So I wanted to save your time that's all,


For the release, there are a lot of people waiting for the same issue, so I don't really know

**Comment by Murtaza-Tn** [comment]
> > @zezo357 @SergeShkurko  Could you please provide an estimated timeline for when the fix will be published on pub.dev?
> 
> I am not the maintainer of the package, I just saw your issue and I had it too,
> 
> So I wanted to save your time that's all,
> 
> For the release, there are a lot of people waiting for the same issue, so I don't really know

Thanks a bunch for chiming in! Your shared experience saved me some serious time.

**Comment by Murtaza-Tn** [comment]
The issue is fixed in the repository..
