### ISSUE TITLE
Unable to load PDF file on Macos: PlatformException(RENDER_ERROR, Invalid PDF format, null, null)

### ISSUE THREAD

**Issue by neverCase** [ScerIO/packages.flutter#520]
**Describe the bug**
Pdfx doesn't work on Macos, it shows error: PlatformException(RENDER_ERROR, Invalid PDF format, null, null).
But it works on my iphone.
Is there any case could help me to fix this problem?

**devices**
 - device-1: iPhone 12 pro, 17.3
 - device-2: macos 14.1.1

**Comment by OziTFA** [comment]
what is the solution for this ?

**Comment by neverCase** [comment]
When i use PdfDocument.openData(tmp), this error occurs again。
